config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "users/show" => "users#show"

  resources :products
end

app/views/layouts/_footer.html.haml
%footer.footer
  - if user_signed_in?
    .container
      %ul.list-unstyled.list-inline.text-center.py-2
        %li.list-inline-item
          %h5.mb-1 Thank you for visiting
        %li.list-inline-item
          %a.btn.btn-outline-light{:href => "#!"} Log out !
  - else
    .container
      %ul.list-unstyled.list-inline.text-center.py-2
        %li.list-inline-item
          %h5.mb-1 Register for free
        %li.list-inline-item
          %a.btn.btn-outline-light{:href => "#!"} Sign up !
  .footer-copyright.text-center.py-3
    Wellcome to
    %a{:href => "#"} - Studio +modelers -

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  %a.navbar-brand{:href => "#"} Studio +modeler
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          Home
          %span.sr-only (current)
      - if user_signed_in?
        %li.nav-item.active
          = link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link")
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            User
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to( 'Mypage', users_show_path, {class: "dropdown-item"} )
            = link_to( 'Edit', edit_user_registration_path, {class: "dropdown-item"} )
      - else
        %li.nav-item.active
          %a.nav-link{"data-target" => "#signUpModal", "data-toggle" => "modal", :type => "button"} Sign Up
        %li.nav-item
          %a.nav-link{"data-target" => "#logInModal", "data-toggle" => "modal", :type => "button"} Log In
      %li.nav-item
        %a.nav-link{:href => "/products/new"} New product
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title StudioModelers
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/navbar'
    - unless user_signed_in?
      = render partial: 'devise/registrations/new'
      = render partial: 'devise/sessions/new'
    = yield
    = render 'layouts/footer'